### ISSUE TITLE
Tradeshop null, unhandled exception 'ts' with "CARROTS"

### ISSUE THREAD

**Issue by HarbourHeading** [SparklingComet/TradeShop#102]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [ yes ] I have checked for similar issues.
- [ yes ] I have updated to the [latest TradeShop version][download].
- [ yes ] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type
Typing "CARROTS" into shop, gives null, unhandled exception 'ts'.

- [ yes ] Bug Report
- [ ] Feature Request

### Description
Making a shop, adding "carrots" as product and whatever as cost, returns null (air in-game).
This can be recreated, by simply making a shop and adding the product "carrots".
Logs output:
null
org.bukkit.command.CommandException: Unhandled exception executing command 'ts' in plugin TradeShop v2.2.5-STABLE
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$6763/0x00000000b110a020.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3049/0x00000000246b4b40.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:826) [?:1.8.0_302]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_302]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_302]
	at org.shanerx.tradeshop.objects.ShopChest.hasStock(ShopChest.java:173) ~[?:?]
	at org.shanerx.tradeshop.objects.Shop.updateStatus(Shop.java:781) ~[?:?]
	at org.shanerx.tradeshop.objects.Shop.updateSignLines(Shop.java:714) ~[?:?]
	at org.shanerx.tradeshop.objects.Shop.updateSign(Shop.java:641) ~[?:?]
	at org.shanerx.tradeshop.objects.Shop.addCost(Shop.java:455) ~[?:?]
	at org.shanerx.tradeshop.commands.CommandRunner.addCost(CommandRunner.java:522) ~[?:?]
	at org.shanerx.tradeshop.commands.CommandCaller.onCommand(CommandCaller.java:97) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-786]
	... 21 more

Errors also appear when breaking the shop with this error.
Logs output:
[20:53:46 ERROR]: Could not pass event PlayerInteractEvent to TradeShop v2.2.5-STABLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_302]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_302]
        at org.shanerx.tradeshop.objects.ShopChest.hasStock(ShopChest.java:173) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateStatus(Shop.java:781) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateSignLines(Shop.java:714) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateSign(Shop.java:641) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.fixAfterLoad(Shop.java:598) ~[?:?]
        at org.shanerx.tradeshop.utils.JsonConfiguration.loadShop(JsonConfiguration.java:235) ~[?:?]
        at org.shanerx.tradeshop.listeners.ShopTradeListener.onBlockInteract(ShopTradeListener.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.EventExecutor$$Lambda$4646/0x00000000b19be940.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:189) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$6763/0x00000000b110a020.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3049/0x00000000246b4b40.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:826) [?:1.8.0_302]

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
This seems to already be fixed in the latest DEV code which should be released as V2.3.0 soon, however to make sure I need to know how you are adding Carrots as a product? (directly to the sign, with /ts addproduct while holding the item, or with /ts addproduct <amount> <type>)

Also a side question, what is `Carrots` the carrot item uses the type `Carrot`?

**Comment by HarbourHeading** [comment]
> This seems to already be fixed in the latest DEV code which should be released as V2.3.0 soon, however to make sure I need to know how you are adding Carrots as a product? (directly to the sign, with /ts addproduct while holding the item, or with /ts addproduct )
> 
> Also a side question, what is `Carrots` the carrot item uses the type `Carrot`?

I’m guessing V2.3.0 is coming out later and not already out?

It is added with the command <amount> <item>

It is indeed meant to be ”carrot”, so what I don’t know, is the reason the option ”carrots” exist?

**Comment by KillerOfPie** [comment]
Just found it, `Carrots` is the Material value for the carrot plant when it is planted. This and a bunch of other values like `Potatoes` and `Bamboo Sapling` need to be removed, not sure how I will do this however.

This is not throwing any errors in the latest build so this may be something I try to fix in the next version.

And Yes 2.3.0 should be coming out later this month.

**Comment by KillerOfPie** [comment]
I found the below items that I'll remove from the list, let me know if you find any more.

```
CARROTS,
    POTATOES,
    BAMBOO_SAPLING,
    AIR,
    ATTACHED_MELON_STEM,
    ATTACHED_PUMPKIN_STEM,
    BEETROOTS,
    BIG_DRIPLEAF_STEM,
    CANDLE_CAKE,
    WHITE_CANDLE_CAKE,
    ORANGE_CANDLE_CAKE,
    MAGENTA_CANDLE_CAKE,
    LIGHT_BLUE_CANDLE_CAKE,
    YELLOW_CANDLE_CAKE,
    LIME_CANDLE_CAKE,
    PINK_CANDLE_CAKE,
    GRAY_CANDLE_CAKE,
    LIGHT_GRAY_CANDLE_CAKE,
    CYAN_CANDLE_CAKE,
    PURPLE_CANDLE_CAKE,
    BLUE_CANDLE_CAKE,
    BROWN_CANDLE_CAKE,
    GREEN_CANDLE_CAKE,
    RED_CANDLE_CAKE,
    BLACK_CANDLE_CAKE,
    WALL_BANNER,
    WHITE_WALL_BANNER,
    ORANGE_WALL_BANNER,
    MAGENTA_WALL_BANNER,
    LIGHT_BLUE_WALL_BANNER,
    YELLOW_WALL_BANNER,
    LIME_WALL_BANNER,
    PINK_WALL_BANNER,
    GRAY_WALL_BANNER,
    LIGHT_GRAY_WALL_BANNER,
    CYAN_WALL_BANNER,
    PURPLE_WALL_BANNER,
    BLUE_WALL_BANNER,
    BROWN_WALL_BANNER,
    GREEN_WALL_BANNER,
    RED_WALL_BANNER,
    BLACK_WALL_BANNER,
    BRAIN_CORAL_WALL_FAN,
    TUBE_CORAL_WALL_FAN,
    BUBBLE_CORAL_WALL_FAN,
    FIRE_CORAL_WALL_FAN,
    HORN_CORAL_WALL_FAN,
    DEAD_BRAIN_CORAL_WALL_FAN,
    DEAD_TUBE_CORAL_WALL_FAN,
    DEAD_BUBBLE_CORAL_WALL_FAN,
    DEAD_FIRE_CORAL_WALL_FAN,
    DEAD_HORN_CORAL_WALL_FAN,
    BUBBLE_COLUMN,
    CAVE_AIR,
    CAVE_VINES_PLANT,
    COCOA,
    OAK_WALL_SIGN,
    SPRUCE_WALL_SIGN,
    BIRCH_WALL_SIGN,
    JUNGLE_WALL_SIGN,
    ACACIA_WALL_SIGN,
    DARK_OAK_WALL_SIGN,
    CRIMSON_WALL_SIGN,
    WARPED_WALL_SIGN,
    DRAGON_WALL_HEAD,
    END_GATEWAY,
    END_PORTAL,
    FROSTED_ICE
```

**Comment by KillerOfPie** [comment]
This is fixed and will be in the 2.3.0 release
b702d31dcb1a5534d26fcaefdcc000b1e3dcaa2a

**Comment by SparklingComet** [comment]
@KillerOfPie I confess myself confused. Could you elaborate on the criterium for exclusion in your list of `Material` entries?

**Comment by KillerOfPie** [comment]
> @KillerOfPie I confess myself confused. Could you elaborate on the criterium for exclusion in your list of `Material` entries?

These are items that cannot be received by a player in any way. They are all(I think) thing that exist in the world, but become a different item when broken or put into a players inventory in another way.

I.E. When a `SPRUCE_WALL_SIGN` is broken it drops a `SPRUCE_SIGN` item. 

To find them I just went through the material list [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html), and if i could not find it in the creative inventory or give it to myself with the `give` command then it went into the list.
