### ISSUE TITLE
/ts who error in log

### ISSUE THREAD

**Issue by Hoshxx** [SparklingComet/TradeShop#155]
### Stack trace

[17:32:11 INFO]: Papishori issued server command: /ts who
[17:32:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ts' in plugin TradeShop v2.6.1-DEV
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[paper-1.20.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-82]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.StackOverflowError
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsersExcluding(Shop.java:729) ~[TradeShop-2.6.1-DEV (8).jar:?]
	at org.shanerx.tradeshop.shop.Shop.getUsers(Shop.java:717) ~[TradeShop-2.6.1-DEV (8).jar:?]

### Plugin list

Essentials
LuckPerms
ProtocolLib
RedProtect
TradeShop

### Actions to reproduce (if known)

Typing /ts who gives out error in chat saying "An internal error occurred while attempting to perform this command".

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

Paper version 1.20.1 #82 
TradeShop 2.6.1-DEV

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by KillerOfPie** [comment]
This is fixed in the latest dev build #156  

https://jenkins.killerofpie.com/job/tradeshop/
