### ISSUE TITLE
[trade] in a sign does not work and says "Error:Empty line"

### ISSUE THREAD

**Issue by Ironsicecream** [SparklingComet/TradeShop#167]
### Expected behavior

I expect to see [trade]  two line breaks and <Incomplete> on the tradeshop sign

### Observed/Actual behavior

![image](https://github.com/user-attachments/assets/52b2db3d-0c01-43ef-944c-fb05deee60bf)

### Steps/models to reproduce

none

### Plugin list

.

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

19.08 21:44:30 [Server] INFO This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
19.08 21:44:30 [Server] INFO You are running the latest version

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by Ironsicecream** [comment]
9.08 21:46:16 [Server] ERROR [TradeShop] com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 26 column 177 path $.l::Shop::-34.0::1.0::14.0.product[0].itemStack.meta.display-name
19.08 21:46:16 [Server] INFO --------------------------------------------------------------------------------------
19.08 21:46:16 [Server] INFO {
19.08 21:46:16 [Server] INFO "l::Shop::-34.0::1.0::14.0": {
19.08 21:46:16 [Server] INFO "shopLoc": {
19.08 21:46:16 [Server] INFO "div": "::",
19.08 21:46:16 [Server] INFO "worldName": "Shop",
19.08 21:46:16 [Server] INFO "x": -34.0,
19.08 21:46:16 [Server] INFO "y": 1.0,
19.08 21:46:16 [Server] INFO "z": 14.0
19.08 21:46:16 [Server] INFO },
19.08 21:46:16 [Server] INFO "owner": {
19.08 21:46:16 [Server] INFO "player": "57c0add0-8f30-4fda-b2ea-8cbad4bb3417",
19.08 21:46:16 [Server] INFO "role": "OWNER"
19.08 21:46:16 [Server] INFO },
19.08 21:46:16 [Server] INFO "managers": [],
19.08 21:46:16 [Server] INFO "members": [],
19.08 21:46:16 [Server] INFO "shopType": "TRADE",
19.08 21:46:16 [Server] INFO "product": [
19.08 21:46:16 [Server] INFO {
19.08 21:46:16 [Server] INFO "itemStack": {
19.08 21:46:16 [Server] INFO "==": "org.bukkit.inventory.ItemStack",
19.08 21:46:16 [Server] INFO "v": 3465,
19.08 21:46:16 [Server] INFO "type": "NETHERITE_SHOVEL",
19.08 21:46:16 [Server] INFO "meta": {
19.08 21:46:16 [Server] INFO "==": "ItemMeta",
19.08 21:46:16 [Server] INFO "meta-type": "UNSPECIFIC",
19.08 21:46:16 [Server] INFO "display-name": "{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#60788C\",\"text\":\"M\"
19.08 21:46:16 [Server] INFO com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 26 column 177 path $.l::Shop::-34.0::1.0::14.0.product[0].itemStack.meta.display-name
19.08 21:46:16 [Server] INFO at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar:?]
19.08 21:46:16 [Server] INFO at com.google.gson.JsonParser.parseReader(JsonParser.java:102) ~[gson-2.10.jar:?]
19.08 21:46:16 [Server] INFO at com.google.gson.JsonParser.parseReader(JsonParser.java:70) ~[gson-2.10.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.Json.JsonConfiguration.loadFile(JsonConfiguration.java:115) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.Json.JsonShopConfiguration.loadFile(JsonShopConfiguration.java:145) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.Json.JsonConfiguration.<init>(JsonConfiguration.java:63) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.Json.JsonShopConfiguration.<init>(JsonShopConfiguration.java:51) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.DataStorage.getShopConfiguration(DataStorage.java:292) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.DataStorage.getShopConfiguration(DataStorage.java:287) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.data.storage.DataStorage.loadShopFromSign(DataStorage.java:180) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.shop.Shop.loadShop(Shop.java:168) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.shop.Shop.loadShop(Shop.java:178) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.player.ShopUser.findObservedShop(ShopUser.java:91) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.commands.commandrunners.ShopItemSubCommand.setSide(ShopItemSubCommand.java:127) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.commands.SubCommand.runSubCommand(SubCommand.java:118) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.shanerx.tradeshop.commands.CommandCaller.onCommand(CommandCaller.java:84) ~[TradeShop-2.6.1-STABLE.jar:?]
19.08 21:46:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
19.08 21:46:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
19.08 21:46:16 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.1.jar:git-Paper-196]
19.08 21:46:16 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-196]
19.08 21:46:16 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
19.08 21:46:16 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
19.08 21:46:16 [Multicraft] Skipped 54 lines due to rate limit (160/s)

**Comment by Ironsicecream** [comment]
Above comment is what shows in the console when I try to make a trade shop in this certain chunk
