### ISSUE TITLE
[BUG] InventoryMoveItemEvent error with composters and hoppers

### ISSUE THREAD

**Issue by jackson-57** [SparklingComet/TradeShop#68]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here](https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels).

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

I noticed that whenever a piece of bonemeal is taken from a full composter by a hopper, TradeShop throws an error in the console. Neither the composter or the hopper had any sort of sign on them.
Any ideas on why this could be happening, and are there any workarounds in the meantime?

### Console Error

<details> 
  <summary> </summary>

`
[09:23:51] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to TradeShop v2.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:308) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$3(TileEntityHopper.java:270) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119) ~[?:?]
	at java.util.Spliterators$IntArraySpliterator.tryAdvance(Spliterators.java:1041) ~[?:?]
	at java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.IntPipeline.anyMatch(IntPipeline.java:513) ~[?:?]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:269) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$0(TileEntityHopper.java:118) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:139) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:402) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NullPointerException
	at org.shanerx.tradeshop.listeners.ShopProtectionListener.onInventoryMoveItem(ShopProtectionListener.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.1.14.4.jar:git-Spigot-56f8471-56118c6]
	... 26 more
`

</details>

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
@SparklingComet Looks like a problem with the list there, if you can look into this while you're doing the add-on stuff, if not let me know when you finish and I'll take a look.

**Comment by jackson-57** [comment]
any updates on this?

**Comment by KillerOfPie** [comment]
@jackson-57, @SparklingComet hasn't gotten back to me yet. I think he's busy with school atm. I have to wait on him to finish the add-on updates before I can do any work.

If you would like a temporary solution, you should be able to remove hoppers from the inventory list and toggle any hopper settings and that may prevent the error. Not entirely well if or how well this will work though

**Comment by jackson-57** [comment]
ok, thanks!

**Comment by KillerOfPie** [comment]
@jackson-57 this should be fixed in the 2.2.2 update that should be coming out soon
