### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DarkChromaMC** [SparklingComet/TradeShop#89]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [ YES] I have checked for similar issues.
- [YES ] I have updated to the [latest TradeShop version][download].
- [YES ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

Shops **can not** sell shulkers for any cost in the latest plugin version. It works on the previous version however. I found the issue is only prevalent for shulkers, other items work fine.

### Console Error

>.... [00:40:57 ERROR]: Could not pass event PlayerInteractEvent to TradeShop v2.2.2-STABLE
java.lang.NullPointerException: null
at org.shanerx.tradeshop.utils.Utils.getItems(Utils.java:488) ~[?:?]
at org.shanerx.tradeshop.objects.ShopChest.hasStock(ShopChest.java:154) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateStatus(Shop.java:778) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateSignLines(Shop.java:711) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateSign(Shop.java:639) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.fixAfterLoad(Shop.java:596) ~[?:?]
at org.shanerx.tradeshop.utils.JsonConfiguration.loadShop(JsonConfiguration.java:210) ~[?:?]
at org.shanerx.tradeshop.listeners.ShopTradeListener.onBlockInteract(ShopTradeListener.java:74) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-208]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:154) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1385) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-208]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
>.... [00:40:57 ERROR]: Could not pass event BlockBreakEvent to TradeShop v2.2.2-STABLE
java.lang.NullPointerException: null
at org.shanerx.tradeshop.utils.Utils.getItems(Utils.java:488) ~[?:?]
at org.shanerx.tradeshop.objects.ShopChest.hasStock(ShopChest.java:154) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateStatus(Shop.java:778) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateSignLines(Shop.java:711) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.updateSign(Shop.java:639) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.fixAfterLoad(Shop.java:596) ~[?:?]
at org.shanerx.tradeshop.utils.JsonConfiguration.loadShop(JsonConfiguration.java:210) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.loadShop(Shop.java:150) ~[?:?]
at org.shanerx.tradeshop.objects.Shop.loadShop(Shop.java:170) ~[?:?]
at org.shanerx.tradeshop.listeners.ShopProtectionListener.onBlockBreak(ShopProtectionListener.java:163) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-208]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-208]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:173) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1385) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-208]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-208]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by Fakhri1999** [comment]
I also get this bug on my server. I just want to add info, you can sell shulker_shell, but can't sell shulker_box

**Comment by ess3sq** [comment]
Try setting up the shop with commands, not by editing the sign.

**Comment by SparklingComet** [comment]
Try setting up the shop with commands, not by editing the sign

**Comment by DarkChromaMC** [comment]
> Try setting up the shop with commands, not by editing the sign

Have tried this already. Got the same error as above.

**Comment by KillerOfPie** [comment]
This is more than likely due to me forgetting to add back in the proper checks after making the trading fixes, will look at it this weekend.

**Comment by DarkChromaMC** [comment]
Have tried using commands, still same error.

**Comment by KillerOfPie** [comment]
This was a very simple error due to not checking if an item in the inventory was null before checking if it was a shulker, will be fixed in 2.2.3
