### ISSUE TITLE
[BUG] Console spam error

### ISSUE THREAD

**Issue by DarkChromaMC** [SparklingComet/TradeShop#98]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [ YES] I have checked for similar issues.
- [ YES] I have updated to the [latest TradeShop version][download].
- [ ?] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

I get this error in console. No clue what it means. Please look into this, and let me know how I can fix this, or whether this is a bug from the plugin itself.

Thank you

### Console Error

<details> 
  <summary> </summary>

java.lang.NullPointerException: null
        at org.shanerx.tradeshop.objects.ShopChest.resetOldName(ShopChest.java:112) ~[?:?]
        at org.shanerx.tradeshop.listeners.ShopProtectionListener.onChestOpen(ShopProtectionListener.java:229) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1594) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Airplane-"d7d1626"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

</details>

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by SparklingComet** [comment]
What plugin and what Minecraft version are you running?

**Comment by DarkChromaMC** [comment]
TradeShop2.2.5-STABLE

**Comment by DarkChromaMC** [comment]
Java 1.16.5 running a fork of Tuinity

**Comment by SparklingComet** [comment]
Can you please try the latest dev version  (experimental pre-release) and see if the issue persists?

https://github.com/Tradeshop/TradeShop/releases/tag/tradeshop-2.3.0-DEV-2020-12-06T19.04.47

**Comment by SparklingComet** [comment]
@lbrunton did you have the opportunity to test it out?

**Comment by SparklingComet** [comment]
Closing due to inactivity

**Comment by DarkChromaMC** [comment]
Hello, 

Sorry for the very late response. I have tested the dev version that you attached above for 48 hours, and I recieve this different console spam error.

`[06:08:52 ERROR]: Could not pass event PlayerInteractEvent to TradeShop v2.3.0-DEV
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at org.shanerx.tradeshop.objects.ShopChest.hasStock(ShopChest.java:173) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateStatus(Shop.java:818) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateSignLines(Shop.java:750) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.updateSign(Shop.java:677) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.fixAfterLoad(Shop.java:632) ~[?:?]
        at org.shanerx.tradeshop.utils.data.JsonConfiguration.loadShop(JsonConfiguration.java:261) ~[?:?]
        at org.shanerx.tradeshop.utils.data.DataStorage.loadShopFromSign(DataStorage.java:54) ~[?:?]
        at org.shanerx.tradeshop.objects.Shop.loadShop(Shop.java:155) ~[?:?]
        at org.shanerx.tradeshop.objects.ShopChest.getShop(ShopChest.java:271) ~[?:?]
        at org.shanerx.tradeshop.listeners.ShopProtectionListener.onChestOpen(ShopProtectionListener.java:233) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1619) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by SparklingComet** [comment]
So the previously posted exception no longer appears, is that correct?

Also please describe the circumstances that lead to this stack trace.

**Comment by DarkChromaMC** [comment]
I don't know how the error occurs, but I have another question that I noticed the dev version of the plugin may have introduced. What is this, and how do I disable it? 
![image](https://user-images.githubusercontent.com/68839442/109733209-814def00-7c23-11eb-9a09-3fd4d3fae59e.png)

**Comment by KillerOfPie** [comment]
> I don't know how the error occurs, but I have another question that I noticed the dev version of the plugin may have introduced. What is this, and how do I disable it?
> ![image](https://user-images.githubusercontent.com/68839442/109733209-814def00-7c23-11eb-9a09-3fd4d3fae59e.png)

The screenshot shows you the statuses of all the shops you are involved with, currently not able to disable it but we'll see if we can get that fixed for the 2.3.0 release.

**Comment by SparklingComet** [comment]
> I don't know how the error occurs, but I have another question that I noticed the dev version of the plugin may have introduced. What is this, and how do I disable it?

I have introduced a setting to disable it (will be in the next (pre-)release (2.3.0; #92 ). But I fear I do need more information on this stacktrace. When does it occur? When you right click a sign, when you attempt to open a chest, when you trade...?

**Comment by DarkChromaMC** [comment]
How can I install the #92 ?

**Comment by SparklingComet** [comment]
> How can I install the #92 ?

I have freshly compiled the latest dev build for you, see link below. Please test whether you are still experiencing the error above, as well as give feedback on the newly added `/ts togglestatus` command which disables the message above.

https://github.com/Tradeshop/TradeShop/releases/tag/tradeshop-2.3.0-DEV-2021-03-08T13.29.27.jar

**Comment by DarkChromaMC** [comment]
Is it possible to completely disable the feature? The notifications still appear even after the chestshop is removed (using worldedit). I use the arm plugin to handle region shops, and if a player has their shop reset, with chestshops inside, those chestshops are still getting notifications. I really prefer not having the feature enabled for all players, as it spams their chat every time they log.

**Comment by SparklingComet** [comment]
They are turned off by default.

**Comment by SparklingComet** [comment]
Closing due to inactivity (again).

**Comment by SparklingComet** [comment]
Closing issue. @lbrunton  can reopen it in case there are still problems.
